import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full bg-gray-900 text-white p-4 flex items-center justify-between">
          <a href="#main-content" className="sr-only focus:not-sr-only">Skip to content</a>
          <div className="font-bold text-lg">HAQQ-Studios</div>
          <div>web1</div>
        </nav>
        <main id="main-content">{children}</main>
      </body>
    </html>
  )
}
